name: Python Style Checker

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

permissions:
  contents: read

jobs:
  pycodestyle:
    name: Run pycodestyle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install pycodestyle
        run: |
          python -m pip install --upgrade pip
          pip install pycodestyle

      - name: Run pycodestyle
        run: |
          pycodestyle .
        continue-on-error: true
